If:
  PathMatch: .*/dev/cp/.*
CompileFlags:
  Add:
    - -O2
    - -Wall
    - -Wextra
    - -Wpedantic
    - -Wshadow
    - -Wconversion
    - -Wformat=2
    - -Wfloat-equal
    - -Wundef
    - -fdiagnostics-color=always
    - -DLOCAL
Diagnostics:
  ClangTidy:
    Remove: '*'
