local bufremove = require('config.bufremove')

vim.keymap.set('n', '<leader>bd', function()
    bufremove()
end, { desc = 'delete buffer' })
vim.keymap.set('n', '<leader>bw', function()
    bufremove(true)
end, { desc = 'wipeout buffer' })
vim.keymap.set('n', '<c-w>x', function()
    bufremove()
end, { desc = 'delete buffer' })
