#!/bin/sh

at_root=
directories=
all=

while [ "$#" -gt 0 ]; do
  case "$1" in
  --root)
    at_root=1
    shift
    ;;
  --directories)
    directories=1
    shift
    ;;
  --all)
    all=1
    shift
    ;;
  *) break ;;
  esac
done

find_vcs_root() {
  dir=$(pwd -P) || return 1
  while :; do
    if [ -e "$dir/.git" ] || [ -e "$dir/.jj" ]; then
      printf '%s\n' "$dir"
      return 0
    fi
    parent=$(dirname "$dir")
    [ "$parent" != "$dir" ] || return 1
    dir=$parent
  done
}

root=$(find_vcs_root) || root=
if [ -n "$root" ] && [ -n "$at_root" ]; then
  cd "$root" || exit 1
fi

if [ -n "$directories" ]; then
  if command -v fd >/dev/null 2>&1; then
    if [ -n "$root" ]; then
      [ -z "$all" ] || exec fd --type directory --hidden --no-ignore \
        --exclude .git --exclude .jj "$@"
      exec fd --type directory --hidden --no-require-git \
        --exclude .git --exclude .jj "$@"
    fi
    exec fd --type directory --hidden --no-ignore "$@"
  fi
  exec find . -type d -print
fi

if ! command -v rg >/dev/null 2>&1; then
  case " $* " in
  *' --files '*)
    exec find . -type f -print
    ;;
  esac
  printf '%s\n' 'list: ripgrep is required for content search' >&2
  exit 127
fi

if [ -n "$root" ]; then
  if [ -n "$all" ]; then
    set -- --hidden --no-config --no-ignore \
      --glob '!.git/' --glob '!.jj/' "$@"
  else
    set -- --hidden --no-config --no-ignore-dot --no-require-git \
      --glob '!.git/' --glob '!.jj/' "$@"
  fi
else
  set -- --hidden --no-config --no-ignore "$@"
fi

exec rg "$@"
